### ISSUE TITLE
extensionクラスの中でprojectの設定を参照したい

### ISSUE THREAD

**Issue by yuki-teraoka** [int128/gradle-ssh-plugin#146]
extensionとして作成したクラスの中でprojectオブジェクトを取得することは出来ないでしょうか。

色々試した結果、gradleのparallel実行を禁止して、taskGraph.beforeTaskの中でstaticなフィールドにprojectを突っ込んでなんとか参照することができたのですが、コレはあんまりにも酷いやり方ですよね。

**Comment by int128** [comment]
色々調べてみましたが，現在のバージョンでは不可能でした．次のバージョンでextensionの仕組みを見直す予定です．

**Comment by int128** [comment]
下記のようにクラス変数を経由させるとextensionからprojectにアクセスできました．今後のバージョンでは改善したいと思います．

(in English) We can access `project` property from an extension by using the static property like following code. It will be able to access without this workaround in the future release.

```groovy
// build.gradle
ProjectLocator.project = project

task example << {
    def x = randomInt()
    ssh.run {
        settings {
            extensions = [ProjectInjection, Hoge]
        }
        session(remotes.localhost) {
            doSomething()
        }
    }
}
```

```groovy
// buildSrc/src/main/groovy/extensions.groovy
import org.gradle.api.Project

class ProjectLocator {
    static Project project
}

class ProjectInjection {
    Project getProject() {
        ProjectLocator.project
    }
}

class ExampleExtension {
    void doSomething() {
        println project.name
    }
}
```

**Comment by yuki-teraoka** [comment]
サンプルコードまでありがとうございます。
次期バージョン、期待しております。

私も同じような実装で、マルチプロジェクトで利用しているのでtaskGraph.beforeTaskをで差し替えるようにしています。説明不足ですみません。

**Comment by int128** [comment]
バージョン1.1.1から map で extension を追加できるようになりました．これでマルチプロジェクト構成の場合も正しいprojectを参照できると思います．詳しくは下記を参照ください．
https://gradle-ssh-plugin.github.io/user-guide.html#dsl-extension-system

Since v1.1.1, we can extends DSL by a map of method name and closure. It should fix the problem in case of the multi-project configuration. See following for details:
https://gradle-ssh-plugin.github.io/user-guide.html#dsl-extension-system

**Comment by mitoma** [comment]
:star:

**Comment by yuki-teraoka** [comment]
@int128 早速対応いただき、ありがとうございます！
